[project]
name = "maigic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.1",
    "ruff>=0.6.5",
]
[tool.ruff.lint]
select = ["ALL"]
