version: 2.1

executors:
  my-docker-executor:
    docker:
      - image: cimg/python:3.11.10

jobs:
  build:
    executor: my-docker-executor
    steps:
      - checkout

      - run:
          name: Get uv via curl and install it
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            source $HOME/.cargo/env

      - run:
          name: Set uv path as env variable and reload bash
          command: |
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source ~/.bashrc

      - persist_to_workspace:
          root: ~/.local
          paths:
            - bin/uv

  test:
    executor: my-docker-executor
    steps:
      - checkout

      - attach_workspace:
          at: ~./local

      - run:
          name: Set-up project dependencies
          command: uv sync

      - run:
          name: Format python files with ruff
          command: uv run ruff check . --fix

      - run:
          name: Run test files
          command: uv run pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
